Backend-Homework-Pronia/Models/Color.cs
using Backend_Homework_Pronia.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend_Homework_Pronia.Models
{
    public class Color:BaseEntity
    {
        [Required,StringLength(maximumLength:25)]
        public string Name { get; set; }
        public List<PlantColor> PlantColors { get; set; }

    }
}

Backend-Homework-Pronia/Areas/ProniaAdmin/Controllers/ColorController.cs
using Backend_Homework_Pronia.DAL;
using Backend_Homework_Pronia.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Backend_Homework_Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class ColorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ColorController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Color> model = _context.Colors.ToList();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Color color)
        {
            if (!ModelState.IsValid) return View();
            Color existed = _context.Colors.FirstOrDefault(x =>
            x.Name.ToLower().Trim() == color.Name.ToLower().Trim());
            if (existed != null)
            {
                ModelState.AddModelError("Name", "This color already exists");
                return View();
            }
            _context.Colors.Add(color);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult Edit(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Color existed = _context.Colors.FirstOrDefault(x => x.Id == id);
            if (existed is null) return NotFound();

            return View(existed);
        }
        
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(int? id, Color newColor)
        {
            if (id is null || id == 0) return NotFound();
            if (!ModelState.IsValid) return View();

            Color existed = _context.Colors.FirstOrDefault(x => x.Id == id);
            if (existed is null) return BadRequest();

            bool isDuplicate = _context.Colors.Any(x => x.Name.ToLower().Trim() == newColor.Name.ToLower().Trim());
            if(isDuplicate)
            {
                ModelState.AddModelError("Name", "This color already exists");
                return View();
            }

            _context.Entry(existed).CurrentValues.SetValues(newColor);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Remove(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Color color = await _context.Colors.FirstOrDefaultAsync(x => x.Id == id);

            if (color is null) return NotFound();

            _context.Colors.Remove(color);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult Detail(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Color existed =  _context.Colors.FirstOrDefault(x => x.Id == id);

            if (existed is null) return NotFound();
            return View(existed);
        }
    }
}

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Color/Create.cshtml
@model Color
@{
    ViewData["Title"] = "Create";
}


<div class="main-panel">
    <h1>Create a color</h1>
    <form class="mt-3" method="post" enctype="multipart/form-data">
        <div>
            <label>Color name:</label><br />
            <input asp-for="Name" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
       
        <div class="mt-2">
            <button class="btn btn-success" type="submit">Create</button>
        </div>
    </form>
</div>

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Color/Detail.cshtml
@model Color
@{
    ViewData["Title"] = "Detail";
}
<div>
    <h3>Details of Color</h3>
    <p>Id: @Model.Id</p>
    <p>Color: @Model.Name</p>
</div>

	

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Color/Edit.cshtml
@model Color
@{
    ViewData["Title"] = "Edit";
}


<div class="main-panel d-flex flex-column justify-content-center align-items-center">
    <h1>Edit color</h1>
    <form class="mt-3" method="post">
        <div>
            <label>Color name:</label><br />
            <input asp-for="Name" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="mt-2">
            <button class="btn btn-warning" type="submit">Edit</button>
        </div>
    </form>
</div>

Backend-Homework-Pronia/Areas/ProniaAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
    ViewData["Title"] = "Index";
}

<div class="main-panel">
    <div>
        <a asp-area="proniaadmin" asp-controller="Color" asp-action="Create" class="btn btn-outline-success">Create new color</a>
    </div>
    <div class="table-responsive pt-3">
        <table class="table table-dark">
            <thead>
                <tr>

                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>
                    
                    <th>
                        Settings
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (Color color in Model.OrderByDescending(x => x.Id))
                {
                    <tr>

                        <td>@color.Id</td>

                        <td>@color.Name</td>

                        <td class="d-flex ">
                            <div class="me-2">
                                <a asp-area="ProniaAdmin" asp-controller="color" asp-action="Edit" asp-route-id="@color.Id" class="btn btn-outline-warning">
                                    <i class="mdi mdi-border-color"></i>
                                </a>
                            </div>
                            <div class="me-2">
                                <a asp-area="ProniaAdmin" asp-controller="color" asp-action="Remove" asp-route-id="@color.Id" class="btn btn-outline-danger">
                                    <i class="mdi mdi-delete"></i>
                                </a>
                            </div>
                            <div>
                                <a asp-area="ProniaAdmin" asp-controller="color" asp-action="Detail" asp-route-id="@color.Id" class="btn btn-outline-info">
                                    <i class="mdi mdi-comment-question-outline"></i>
                                </a>
                            </div>
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>